name: Setup AWS credentials
on: [push]
jobs:
  credentials:
    name: Setup AWS credentials
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: List s3 buckets
        run: aws s3api list-buckets
